### ISSUE TITLE
Exa is no longer maintained

### ISSUE THREAD

**Issue by dloranc** [Selleo/commons#11]
## Short overview

Exa is [no longer maintained](https://github.com/ogham/exa/issues/1243), we should use [eza](https://github.com/eza-community/eza).

## ToDo

- [ ] update README.md
- [ ] replace `exa` with `eza` in `setup.sh` (make sure the command works)
- [ ] update aliases in `aliases.sh`

**Comment by qbart** [comment]
Could you make a PR?

**Comment by dloranc** [comment]
Yes, the PR is: https://github.com/Selleo/commons/pull/14
